# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.5.0
_src_path: gh:radio-aktywne/template-database-minio
accountname: radio-aktywne
databasename: minium
description: Broadcast playlists media 💽
docs: true
docsurl: https://radio-aktywne.github.io/minium
envprefix: MINIUM
imagename: databases/minium
port: 10210
registry: true
releases: true
reponame: minium
repourl: https://github.com/radio-aktywne/minium
webport: 10211
